
CanonTest:
	g++ -I../../cpp -I../../cpp/canon ../../cpp/Object.cpp ../../cpp/Temp.cpp ../../cpp/TreePrinter.cpp ../../cpp/HeapManager.cpp ../../cpp/Tree.cpp ../../cpp/canon/Canon.cpp CanonTest.cpp -oCanonTest

RefTest:
	g++ -I../../cpp RefTest.cpp -oRefTest